### ISSUE TITLE
请问能否像“V2EX增强插件”一样，不用手动点击，每天自动领取“今日奖励”？

### ISSUE THREAD

**Issue by jerry011235** [VitoVan/v2excellent.js#2]
1.希望每天自动领取“今日奖励”。
2.觉得“V2EX增强插件”显示文字的位置不太好，应该在用户名的下方，也就是原来“点击领取奖励”的地方，而不是头顶（如图）。
![](http://moefq.com/images/2015/11/28/036864e9be80c3927f31026946f414c2.png)
如果直接复制相关代码，不知道修改文字显示位置的代码在哪，所以希望v2excellent.js集成。
https://greasyfork.org/en/scripts/3452-v2ex增强插件/code

**Comment by VitoVan** [comment]
哈，可以。已加入待办。

**Comment by VitoVan** [comment]
@jerry011235 开了一个帖子讨论这个功能：https://v2ex.com/t/240089

**Comment by VitoVan** [comment]
考虑之后，决定不在主分支上实现这个功能。
不过，新开了一个 branch，里面有自动签到功能，你可以把代码直接拷贝到你的 User Script 插件里。
代码在这里：https://github.com/VitoVan/v2excellent.js/blob/robot/v2excellent.js

**Comment by jerry011235** [comment]
感谢，完全理解您的做法，事实上，你这样做更合乎理性。人本来就是众口难调的，这样既照顾了需要自动签到的朋友，也照顾了想手动点击的朋友，而我发issue的原因只是因为我懒而已－－！今天读完上述帖子的内容后，我最终还是决定手动点击，尊重创造出v2ex的Livid所说的仪式感，也尊重v2excellent.js设计的初衷，感谢！

**Comment by VitoVan** [comment]
@jerry011235 :+1: 也谢谢你引发了这次思考。

**Comment by jerry011235** [comment]
@VitoVan 哈哈！如果懒能引发思考的话，我在考虑是否要将自己变得更懒一点～ ：）
另外我fork了v2excellent.js项目，也包括gh－pages，不是支持静态网页吗？为什么http://jerry011235.github.io/v2excellent.js是404?？而且fork后的项目setting上写着：

``` bash
GitHub Pages
Your site is ready to be published at http://jerry011235.github.io/v2excellent.js.
```

**Comment by VitoVan** [comment]
@jerry011235 对于这个问题，我完全是 GitHub 新手，所以......我也搞不清楚为什么打不开......

**Comment by jerry011235** [comment]
没关系的，兄弟，还是谢谢了！
