### ISSUE TITLE
回复显示的层级太多，建议添加设置项允许自定义层级

### ISSUE THREAD

**Issue by DemoJameson** [VitoVan/v2excellent.js#4]
~~太多回复会干扰阅读，我简单修改了 findParentComment 里循环的次数，只显示一个回复。
相信别人也有这个需求吧 ^_^~~
看来是我理解错了，原来这个脚本是重排了评论，而不是以添加的方式显示回复的，这样就没有困扰了，赞~

**Comment by VitoVan** [comment]
:smile_cat:
