### ISSUE TITLE
用了之后回复翻页导航看不见了

### ISSUE THREAD

**Issue by benzBrake** [VitoVan/v2excellent.js#5]
求修复。Firefox 43.0.2 on Windows 10
![翻页导航看不见了](https://ooo.0o0.ooo/2016/06/03/5751a00d35b56.jpg)

**Comment by VitoVan** [comment]
哇，本以]人用了呢，最近忙於其他事情，好久]有上V2EX了。

多x，@就理。





On Fri, Jun 3, 2016 at 8:15 AM -0700, "Charisma Low" <notifications@github.com<mailto:notifications@github.com>> wrote:


求修复。Firefox 43.0.2 on Windows 10
[翻页导航看不见了]<https://camo.githubusercontent.com/7b60b050099569f5a4273c0bfb69e40fd7efbca8/68747470733a2f2f6f6f6f2e306f302e6f6f6f2f323031362f30362f30332f353735316130306433356235362e6a7067>

―

**Comment by VitoVan** [comment]
已修复：https://github.com/VitoVan/v2excellent.js/commit/202b0ea9d6fd5d6035eabd0c000063960a4ca0da

这个插件本来就是取消了原有的翻页按钮，把所有页面的回复整理之后做了一个回复关系嵌套。
后来V2EX的翻页功能做了调整，现已更新适配。
