### ISSUE TITLE
图片上传网址http://upload.otar.im/打不开

### ISSUE THREAD

**Issue by jerry011235** [VitoVan/v2excellent.js#6]
感谢更新。
1.图片上传网址 http://upload.otar.im/ 打不开
[http://ping.chinaz.com/upload.otar.im](http://ping.chinaz.com/upload.otar.im)
2.回复头像样式需要调整一下。
没登录头像正常（20px），元素名为`img.avatar`，但登录后v2ex的回复头像好像太大了（40px），元素名也变成`Main img.avatar`了。希望统一调整成最大20px。

**Comment by VitoVan** [comment]
登录之后回复头像的样式问题，我这里没有复现呀，可否帮忙截个图（如果附带 Chrome 的 Developer tools 右键 inspect 更好）？

关于图片上传网址，我已经邮件给相关站长了，你有没有好用的替换建议呢？

**Comment by jerry011235** [comment]
你好，“关于头像样式”，非常抱歉，是我自定义v2ex的css的锅，造成误判，现在删除掉就没事了。

至于图床，根据 https://www.v2ex.com/t/130567 的测试，好像只支持 http://imgur.com/ 和新浪微博图床的图片才能显示，其他的图床只能显示为网址。
以下为我收集的图床：
1. https://sm.ms/
2. https://i4.buimg.com/
2. https://imgchr.com/
3. http://jiantuku.com/#/
4. https://moetu.org/
5. http://x.mouto.org/wb/

**Comment by VitoVan** [comment]
Fixed in https://github.com/VitoVan/v2excellent.js/commit/25caa57e32c6da6b82d2044bdfa99baf2f1cd5fb

Thank you!
