### ISSUE TITLE
使用移动端UA，不能完整显示评论

### ISSUE THREAD

**Issue by liyiecho** [VitoVan/v2excellent.js#7]
这是模拟移动端的显示，效果如图所示：
![55619920-392d-4215-af3a-4435b2531deb](https://cloud.githubusercontent.com/assets/5213722/25426120/b8e2c4be-2aa0-11e7-89d2-2052dae0b3fd.png)

只能显示最后一页的评论，之前的评论没有加载，还望修复。

**Comment by VitoVan** [comment]
@liyiecho 多谢！

已经确认是 BUG 了，但是最近几天可能没有时间修复，可能会到五一之后啦~

多谢支持！

**Comment by VitoVan** [comment]
已修复：https://github.com/VitoVan/v2excellent.js/commit/c371220d9a5c271b861d4b2d750cd0ea0fd3c628

但是：**由于移动端的屏幕太小，不建议在移动端使用 V2EXcellent.js，当评论层叠较多时，移动端屏幕无法优雅的显示。**

**Comment by VitoVan** [comment]
![last-shot](https://cloud.githubusercontent.com/assets/1756956/26553722/850c9b30-4452-11e7-9529-fe0b7fe29070.png)
